### PR TITLE
Full Fabric port

### PR DESCRIPTION
**Pull request by IMS212**
should be on a separate branch

has a little flickering when moving the camera, but is otherwise stable

### CODE REVIEW

**Comment by Exopandora** [comment]
Thank you for the pull request! As i already mentioned in #76, i am currently working to restructure the project similar to the [MultiLoader](https://github.com/jaredlll08/MultiLoader-Template) template in order to support both forge and fabric, so this PR will probably need to adapt to it.

**Comment by IMS212** [comment]
Sounds good!

**Comment by IMS212** [comment]
Most of the work here is replacing the simple events with mixins (also has the benefit of removing the needed AT), so most of this can be put in common!

**Comment by Exopandora** [comment]
The project has been restructured and now supports fabric. Thank you for the initial pull request, it really helped to quickly port the mod.

**Comment by IMS212** [comment]
Nice!

**Pull request closed without merging**
